Te auth
Testell/industrial-auth-1 pull request #1
Opened 2024-10-24 18:20 UTC by Testell

2024-10-28 16:32 UTC, jessjno approved these changes
looks good

2024-10-28 16:32 UTC, jessjno commented on app/controllers/comments_controller.rb
nice job incorporating the redirect back and the alert

2024-10-28 16:32 UTC, jessjno commented on app/views/users/show.html.erb
nice formatting

2024-10-28 16:32 UTC, jessjno commented on app/views/photos/_photo.html.erb
formatting looks clean

2024-10-28 16:32 UTC, jessjno commented on app/controllers/photos_controller.rb
good job added the private method

2024-10-29 18:59 UTC, marywebby requested changes
It looks like you're missing the changes needed in the routes.rb file, please make those changes and then re-request me!

2024-10-29 18:59 UTC, marywebby commented on app/controllers/comments_controller.rb
> +      if current_user != @photo.owner && @photo.owner.private? && !current_user.leaders.include?(@comment.owner)
Good job making the changes here!

2024-10-29 18:59 UTC, marywebby commented on app/controllers/photos_controller.rb
> +  before_action :ensure_current_user_is_owner, only: [:destroy. :update, :edit]
👍

2024-10-29 18:59 UTC, marywebby commented on app/views/photos/_photo.html.erb
> +      <% if current_user == photo.owner %>
Good job with the linking back!

2024-10-29 18:59 UTC, marywebby commented on app/views/users/show.html.erb
> +<% if current_user == @user || !@user.private? || current_user.leaders.include?(@user)  %>
NIce job adding in current_user here!

2024-10-30 19:46 UTC, marywebby approved these changes
Thanks for making those changes!

2024-10-30 20:14 UTC, merged